const initialGames = [
  {
    id: 1,
    title: "God of War",
    imgpath: "",
    release: "20.04.2018",
    publisher: "Sony",
    developer: "Santa Monica Studio",
    platform: "PlayStation 4, PC",
    singleplayer: "Yes",
    multiplayer: "No",
    crossplay: "No",
    category: "Action",
    metacritic: "94/100",
  },
  {
    id: 2,
    title: "The Legend of Zelda: Breath of the Wild",
    imgpath: "",
    release: "03.03.2017",
    publisher: "Nintendo",
    developer: "Nintendo",
    platform: "Nintendo Switch, Wii U",
    singleplayer: "Yes",
    multiplayer: "No",
    crossplay: "No",
    category: "Action-Adventure",
    metacritic: "97/100",
  },
  {
    id: 3,
    title: "Red Dead Redemption 2",
    imgpath: "",
    release: "26.10.2018",
    publisher: "Rockstar Games",
    developer: "Rockstar Games",
    platform: "PlayStation 4, Xbox One, PC",
    singleplayer: "Yes",
    multiplayer: "Yes",
    crossplay: "No",
    category: "Action-Adventure",
    metacritic: "97/100",
  },
  {
    id: 4,
    title: "The Witcher 3: Wild Hunt",
    imgpath: "",
    release: "19.05.2015",
    publisher: "CD Projekt",
    developer: "CD Projekt RED",
    platform: "PlayStation 4, Xbox One, PC, Nintendo Switch",
    singleplayer: "Yes",
    multiplayer: "No",
    crossplay: "No",
    category: "Action-Rollenspiel",
    metacritic: "93/100",
  },
  {
    id: 5,
    title: "Minecraft",
    imgpath: "",
    release: "18.11.2011",
    publisher: "Mojang Studios, Microsoft Studios",
    developer: "Mojang Studios",
    platform: "PlayStation 4, Xbox One, PC, Nintendo Switch, iOS, Android",
    singleplayer: "Yes",
    multiplayer: "Yes",
    crossplay: "Yes",
    category: "Sandbox, Abenteuer",
    metacritic: "93/100",
  },
  {
    id: 6,
    title: "Overwatch",
    imgpath: "",
    release: "24.05.2016",
    publisher: "Blizzard Entertainment",
    developer: "Blizzard Entertainment",
    platform: "PlayStation 4, Xbox One, PC, Nintendo Switch",
    singleplayer: "No",
    multiplayer: "Yes",
    crossplay: "Ja (zwischen Konsolen und PC)",
    category: "First-Person-Shooter",
    metacritic: "91/100",
  },
  {
    id: 7,
    title: "Super Mario Odyssey",
    imgpath: "",
    release: "27.10.2017",
    publisher: "Nintendo",
    developer: "Nintendo",
    platform: "Nintendo Switch",
    singleplayer: "Yes",
    multiplayer: "No",
    crossplay: "No",
    category: "Jump 'n' Run",
    metacritic: "97/100",
  },
  {
    id: 8,
    title: "Assassin's Creed Valhalla",
    imgpath: "",
    release: "10.11.2020",
    publisher: "Ubisoft",
    developer: "Ubisoft Montreal",
    platform: "PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S, PC",
    singleplayer: "Yes",
    multiplayer: "No",
    crossplay: "No",
    category: "Action-Adventure",
    metacritic: "83/100",
  },
  {
    id: 9,
    title: "Cyberpunk 2077",
    imgpath: "",
    release: "10.12.2020",
    publisher: "CD Projekt",
    developer: "CD Projekt RED",
    platform: "PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S, PC",
    singleplayer: "Yes",
    multiplayer: "No",
    crossplay: "No",
    category: "Action-Rollenspiel",
    metacritic: "59/100",
  },
  {
    id: 10,
    title: "Animal Crossing: New Horizons",
    imgpath: "",
    release: "20.03.2020",
    publisher: "Nintendo",
    developer: "Nintendo",
    platform: "Nintendo Switch",
    singleplayer: "Yes",
    multiplayer: "Yes",
    crossplay: "No",
    category: "Lebenssimulation",
    metacritic: "90/100",
  },
];
