export const initialGames = [
  {
    id: 1,
    title: "God of War",
    imgpath:
      "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_AnimalCrossingNewHorizons_image1600w.jpg",
    release: "20.04.2018",
    publisher: "Sony",
    developer: "Santa Monica Studio",
    platform: "PlayStation 4, PC",
    singleplayer: "Yes",
    multiplayer: "No",
    crossplay: "No",
    category: "Action",
    metacritic: "94/100",
    achievements: "37",
  },
  {
    id: 2,
    title: "The Legend of Zelda: Breath of the Wild",
    imgpath:
      "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_AnimalCrossingNewHorizons_image1600w.jpg",
    release: "03.03.2017",
    publisher: "Nintendo",
    developer: "Nintendo",
    platform: "Nintendo Switch, Wii U",
    singleplayer: "Yes",
    multiplayer: "No",
    crossplay: "No",
    category: "Action-Adventure",
    metacritic: "97/100",
    achievements: "-",
  },
  {
    id: 3,
    title: "Red Dead Redemption 2",
    imgpath:
      "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_AnimalCrossingNewHorizons_image1600w.jpg",
    release: "26.10.2018",
    publisher: "Rockstar Games",
    developer: "Rockstar Games",
    platform: "PlayStation 4, Xbox One, PC",
    singleplayer: "Yes",
    multiplayer: "Yes",
    crossplay: "No",
    category: "Action-Adventure",
    metacritic: "97/100",
    achievements: "51",
  },
  {
    id: 4,
    title: "The Witcher 3: Wild Hunt",
    imgpath:
      "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_AnimalCrossingNewHorizons_image1600w.jpg",
    release: "19.05.2015",
    publisher: "CD Projekt",
    developer: "CD Projekt RED",
    platform: "PlayStation 4, Xbox One, PC, Nintendo Switch",
    singleplayer: "Yes",
    multiplayer: "No",
    crossplay: "No",
    category: "Action-Rollenspiel",
    metacritic: "93/100",
    achievements: "78",
  },
  {
    id: 5,
    title: "Minecraft",
    imgpath:
      "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_AnimalCrossingNewHorizons_image1600w.jpg",
    release: "18.11.2011",
    publisher: "Mojang Studios, Microsoft Studios",
    developer: "Mojang Studios",
    platform: "PlayStation 4, Xbox One, PC, Nintendo Switch, iOS, Android",
    singleplayer: "Yes",
    multiplayer: "Yes",
    crossplay: "Yes",
    category: "Sandbox, Abenteuer",
    metacritic: "93/100",
    achievements: "127",
  },
  {
    id: 6,
    title: "Overwatch",
    imgpath:
      "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_AnimalCrossingNewHorizons_image1600w.jpg",
    release: "24.05.2016",
    publisher: "Blizzard Entertainment",
    developer: "Blizzard Entertainment",
    platform: "PlayStation 4, Xbox One, PC, Nintendo Switch",
    singleplayer: "No",
    multiplayer: "Yes",
    crossplay: "Ja (zwischen Konsolen und PC)",
    category: "First-Person-Shooter",
    metacritic: "91/100",
    achievements: "139",
  },
  {
    id: 7,
    title: "Super Mario Odyssey",
    imgpath:
      "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_AnimalCrossingNewHorizons_image1600w.jpg",
    release: "27.10.2017",
    publisher: "Nintendo",
    developer: "Nintendo",
    platform: "Nintendo Switch",
    singleplayer: "Yes",
    multiplayer: "No",
    crossplay: "No",
    category: "Jump 'n' Run",
    metacritic: "97/100",
    achievements: "-",
  },
  {
    id: 8,
    title: "Assassin's Creed Valhalla",
    imgpath:
      "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_AnimalCrossingNewHorizons_image1600w.jpg",
    release: "10.11.2020",
    publisher: "Ubisoft",
    developer: "Ubisoft Montreal",
    platform: "PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S, PC",
    singleplayer: "Yes",
    multiplayer: "No",
    crossplay: "No",
    category: "Action-Adventure",
    metacritic: "83/100",
    achievements: "51",
  },
  {
    id: 9,
    title: "Cyberpunk 2077",
    imgpath:
      "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_AnimalCrossingNewHorizons_image1600w.jpg",
    release: "10.12.2020",
    publisher: "CD Projekt",
    developer: "CD Projekt RED",
    platform: "PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S, PC",
    singleplayer: "Yes",
    multiplayer: "No",
    crossplay: "No",
    category: "Action-Rollenspiel",
    metacritic: "59/100",
    achievements: "44",
  },
  {
    id: 10,
    title: "Animal Crossing: New Horizons",
    imgpath:
      "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_AnimalCrossingNewHorizons_image1600w.jpg",
    release: "20.03.2020",
    publisher: "Nintendo",
    developer: "Nintendo",
    platform: "Nintendo Switch",
    singleplayer: "Yes",
    multiplayer: "Yes",
    crossplay: "No",
    category: "Lebenssimulation",
    metacritic: "90/100",
    achievements: "-",
  },
  {
    id: 11,
    title: "Grand Theft Auto V",
    imgpath:
      "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_AnimalCrossingNewHorizons_image1600w.jpg",
    release: "17.09.2013",
    publisher: "Rockstar Games",
    developer: "Rockstar North",
    platform: "PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S, PC",
    singleplayer: "Yes",
    multiplayer: "Yes",
    crossplay: "No",
    category: "Action-Adventure",
    metacritic: "96/100",
    achievements: "69",
  },
  {
    id: 12,
    title: "FIFA 22",
    imgpath:
      "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_AnimalCrossingNewHorizons_image1600w.jpg",
    release: "01.10.2021",
    publisher: "Electronic Arts",
    developer: "EA Vancouver, EA Romania",
    platform: "PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S, PC",
    singleplayer: "Yes",
    multiplayer: "Yes",
    crossplay: "Yes (between consoles and PC)",
    category: "Sports",
    metacritic: "85/100",
    achievements: "-",
  },
  {
    id: 13,
    title: "Call of Duty: Warzone",
    imgpath:
      "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_AnimalCrossingNewHorizons_image1600w.jpg",
    release: "10.03.2020",
    publisher: "Activision",
    developer: "Infinity Ward, Raven Software",
    platform: "PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S, PC",
    singleplayer: "No",
    multiplayer: "Yes",
    crossplay: "Yes (between consoles and PC)",
    category: "Battle Royale, First-Person Shooter",
    metacritic: "82/100",
    achievements: "137",
  },
  {
    id: 14,
    title: "The Elder Scrolls V: Skyrim",
    imgpath:
      "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_AnimalCrossingNewHorizons_image1600w.jpg",
    release: "11.11.2011",
    publisher: "Bethesda Softworks",
    developer: "Bethesda Game Studios",
    platform:
      "PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S, PC, Nintendo Switch",
    singleplayer: "Yes",
    multiplayer: "No",
    crossplay: "No",
    category: "Action-Rollenspiel",
    metacritic: "94/100",
    achievements: "75",
  },
  {
    id: 15,
    title: "Fortnite",
    imgpath:
      "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_AnimalCrossingNewHorizons_image1600w.jpg",
    release: "25.07.2017",
    publisher: "Epic Games",
    developer: "Epic Games",
    platform:
      "PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S, PC, Nintendo Switch, iOS, Android",
    singleplayer: "No",
    multiplayer: "Yes",
    crossplay: "Yes (between consoles, PC, and mobile)",
    category: "Battle Royale, Third-Person Shooter",
    metacritic: "83/100",
    achievements: "-",
  },
  {
    id: 16,
    title: "Mortal Kombat 11",
    imgpath:
      "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_AnimalCrossingNewHorizons_image1600w.jpg",
    release: "23.04.2019",
    publisher: "Warner Bros. Interactive Entertainment",
    developer: "NetherRealm Studios",
    platform:
      "PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S, PC, Nintendo Switch",
    singleplayer: "Yes",
    multiplayer: "Yes",
    crossplay: "Yes (between consoles and PC)",
    category: "Fighting",
    metacritic: "82/100",
    achievements: "59",
  },
  {
    id: 17,
    title: "Uncharted 4: A Thief's End",
    imgpath:
      "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_AnimalCrossingNewHorizons_image1600w.jpg",
    release: "10.05.2016",
    publisher: "Sony Interactive Entertainment",
    developer: "Naughty Dog",
    platform: "PlayStation 4",
    singleplayer: "Yes",
    multiplayer: "No",
    crossplay: "No",
    category: "Action-Adventure",
    metacritic: "93/100",
    achievements: "68",
  },
  {
    id: 18,
    title: "The Legend of Zelda: Breath of the Wild 2",
    imgpath:
      "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_AnimalCrossingNewHorizons_image1600w.jpg",
    release: "TBD",
    publisher: "Nintendo",
    developer: "Nintendo",
    platform: "Nintendo Switch",
    singleplayer: "Yes",
    multiplayer: "No",
    crossplay: "No",
    category: "Action-Adventure",
    metacritic: "-",
    achievements: "-",
  },
  {
    id: 19,
    title: "Rocket League",
    imgpath:
      "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_AnimalCrossingNewHorizons_image1600w.jpg",
    release: "07.07.2015",
    publisher: "Psyonix",
    developer: "Psyonix",
    platform:
      "PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S, PC, Nintendo Switch",
    singleplayer: "Yes",
    multiplayer: "Yes",
    crossplay: "Yes (between consoles and PC)",
    category: "Sports, Racing",
    metacritic: "86/100",
    achievements: "88",
  },
  {
    id: 20,
    title: "Super Smash Bros. Ultimate",
    imgpath:
      "https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_AnimalCrossingNewHorizons_image1600w.jpg",
    release: "07.12.2018",
    publisher: "Nintendo",
    developer: "Bandai Namco Studios, Sora Ltd.",
    platform: "Nintendo Switch",
    singleplayer: "Yes",
    multiplayer: "Yes",
    crossplay: "No",
    category: "Fighting",
    metacritic: "93/100",
    achievements: "-",
  },
];
